r"""lin_c: the back half of a linear-attention decode layer as ONE dispatch
(design A3 of .claude/plans/open-kernels-phase2-fused-linear-layer.md):

    post (og = bf16(rms(o)*nw*silu(z)))  ->  gemv out  ->  ln (+residual, post-attn norm)

Replaces 3 dispatches over 3 contexts. Same DDR hand-over discipline as lin_a
(`act` carries og and out); kernel bodies are dn_post's, gemv_q4's and ln's,
unchanged. The output is the MoE block's header record (moe_experts): xm at
H_XM and the new residual at H_XRES; the router's slot and sgw are filled by
the host (rout: `copy`; sgw: constant, preloaded).

Shim budget:  col 0: w0 + post in | y0 + post out    col 2: w2 + ln in | y2 + ln out
              col 1: w1 + x (og)  | y1               col 3-7: w | y

Args (see layout.py):
  wout   u8[5242880]     out_proj [2048, 4096] in pool order (RS=2)
  o      f32[4096]       the DeltaNet step's output
  consts u8[C_BYTES]     [lnw | glue side | nw | postln]
  act    u8[A_BYTES]     z read at A_Z; og, out written
  xres   f32[2048]       the layer's input residual
  hdr    u8[H_BYTES]     out: xm at H_XM (bf16), residual after attention at H_XRES (f32)
Build (WSL): python build_design.py designs/lin_layer/lin_c.py designs/lin_layer/build_c
"""

from __future__ import annotations

import hashlib
import sys
from pathlib import Path

import numpy as np
from ml_dtypes import bfloat16

import aie.iron as iron
from aie.iron import Buffer, CompileTime, In, InOut, ObjectFifo, Out, Program, Runtime, TaskGroup, Worker
from aie.iron.controlflow import range_
from aie.iron.device import Tile
from aie.iron.kernel import ExternalFunction
from aie.helpers.taplib import TensorAccessPattern

HERE = Path(__file__).parent
GEMV = HERE.parent / "gemv_q4"
POST = HERE.parent / "dn_post"
LN = HERE.parent / "ln"
sys.path.insert(0, str(HERE.parent.parent))
sys.path.insert(0, str(HERE))
from ironutil import Pipeline, include_dirs  # noqa: E402
from layout import A_BYTES, A_OG, A_OUT, A_Z, C_BYTES, C_NW, C_POSTLN, H_BYTES, H_XM, H_XRES  # noqa: E402

HID = 2048
D = 4096                                      # o / z / og length (32 heads x 128)
G, NG = 1024, 4                               # post: floats per group of 8 heads
# out_proj [2048, 4096], RS=2: 32-chunk bands (K/128), 4 chunks per call
TILE_BYTES, PER_CALL, PER_BAND, BAND_ROWS = 5120, 4, 32, 64
BAND_BYTES = PER_BAND * TILE_BYTES            # 163840
CALL_BYTES = PER_CALL * TILE_BYTES
N_CORES = 8
OUT_PC = HID // BAND_ROWS // N_CORES          # 4 bands per core
WOUT_BYTES = HID // BAND_ROWS * BAND_BYTES    # 5242880


def bt(total: int, off: int, n: int) -> TensorAccessPattern:
    return TensorAccessPattern((1, total), off, [1, 1, 1, n], [0, 0, 0, 1])


@iron.jit(aiecc_flags=["--alloc-scheme=basic-sequential"])
def lin_c(wout: In, o: In, consts: In, act: InOut, xres: In, hdr: Out, *, srchash: CompileTime[int] = 0):
    u8_4k = np.ndarray[(4096,), np.dtype[np.uint8]]
    u8_2k = np.ndarray[(2048,), np.dtype[np.uint8]]
    nw_ty = np.ndarray[(128,), np.dtype[bfloat16]]
    w_ty = np.ndarray[(WOUT_BYTES,), np.dtype[np.uint8]]
    o_ty = np.ndarray[(D,), np.dtype[np.float32]]
    consts_ty = np.ndarray[(C_BYTES,), np.dtype[np.uint8]]
    act_ty = np.ndarray[(A_BYTES,), np.dtype[np.uint8]]
    xres_ty = np.ndarray[(HID,), np.dtype[np.float32]]
    hdr_ty = np.ndarray[(H_BYTES,), np.dtype[np.uint8]]
    elem_ty = np.ndarray[(CALL_BYTES,), np.dtype[np.uint8]]
    x_ty = np.ndarray[(D,), np.dtype[bfloat16]]
    tab_ty = np.ndarray[(2 * D + D // 4,), np.dtype[np.uint8]]       # gemv_q4_tab_bytes(4096)
    band_ty = np.ndarray[(BAND_ROWS,), np.dtype[np.float32]]

    inc = include_dirs() + [str(GEMV), str(POST), str(LN)]
    # ---- kernels
    post_fn = ExternalFunction("post_fn", source_file=str(POST / "post.cc"), arg_types=[u8_4k, u8_4k, nw_ty, u8_2k], include_dirs=inc)
    post_copy = ExternalFunction("post_copy_nw", source_file=str(POST / "post_copy.cc"), arg_types=[u8_4k, nw_ty], include_dirs=inc)
    ks = []
    for i in range(PER_BAND // PER_CALL):
        src = GEMV / f"gemv_q4_p{PER_CALL}b{PER_BAND}r2_k{i}.cc"
        assert src.is_file(), f"{src} (generated by gemv_q4.py)"
        ks.append(ExternalFunction(src.stem, source_file=str(src), arg_types=[elem_ty, tab_ty, band_ty], include_dirs=inc))
    prep = ExternalFunction("gemv_q4_prep_k4096", source_file=str(GEMV / "gemv_q4_prep_k4096.cc"),
                            arg_types=[x_ty, tab_ty], include_dirs=inc)
    ln_fn = ExternalFunction("ln_fn", source_file=str(LN / "ln.cc"), arg_types=[u8_4k] * 8, include_dirs=inc)

    # ---- fifos
    of_pin = ObjectFifo(u8_4k, name="pin", depth=2)      # [nw][o g][z g]...
    of_pout = ObjectFifo(u8_2k, name="pout", depth=2)    # og per group
    of_w = [ObjectFifo(elem_ty, name=f"w{c}", depth=2) for c in range(N_CORES)]
    of_y = [ObjectFifo(band_ty, name=f"y{c}", depth=2) for c in range(N_CORES)]
    of_x = ObjectFifo(x_ty, name="x", depth=1)
    of_lni = ObjectFifo(u8_4k, name="lni", depth=5)      # [x0 x1 | w | a0 a1]  (x, w prefetched; add after the GEMV)
    of_lno = ObjectFifo(u8_4k, name="lno", depth=3)      # [y0 y1 | xn]

    # ---- cores
    def post_body(ain, aout, nwb, f, fc):
        e = ain.acquire(1)
        fc(e, nwb)
        ain.release(1)
        for _ in range_(NG):
            e = ain.acquire(2)
            r = aout.acquire(1)
            f(e[0], e[1], nwb, r)
            aout.release(1)
            ain.release(2)

    def gemv_body(win, xin, yout, tab, fprep, *fns):
        xe = xin.acquire(1)
        fprep(xe, tab)                            # block-quantise og once (gemv_q4.h)
        for _ in range_(OUT_PC):
            ye = yout.acquire(1)
            for fn in fns:
                we = win.acquire(1)
                fn(we, tab, ye)
                win.release(1)
            yout.release(1)
        xin.release(1)

    def ln_body(ain, aout, f):
        e = ain.acquire(5)
        oo = aout.acquire(3)
        f(e[0], e[1], e[3], e[4], e[2], oo[0], oo[1], oo[2])     # ln_fn(x0, x1, a0, a1, w, y0, y1, xn)
        aout.release(3)
        ain.release(5)

    workers = [Worker(post_body, fn_args=[of_pin.cons(), of_pout.prod(), Buffer(nw_ty, name="nwb"), post_fn, post_copy],
                      tile=Tile(0, 3), stack_size=0x1800)]
    for c in range(N_CORES):
        workers.append(Worker(gemv_body, fn_args=[of_w[c].cons(), of_x.cons(), of_y[c].prod(),
                                                  Buffer(tab_ty, name=f"tab{c}"), prep, *ks],
                              tile=Tile(c, 2), stack_size=0x1000))
    workers.append(Worker(ln_body, fn_args=[of_lni.cons(), of_lno.prod(), ln_fn], tile=Tile(2, 3), stack_size=0x1800))

    # ---- host sequence
    def sequence(a_w, a_o, a_consts, a_act, a_xres, c_hdr, pin, pout, w_prods, x_prod, y_conss, lni, lno):
        # 1. post: og -> act[A_OG] (z from act, o from the DeltaNet step)
        pipe = Pipeline(3)
        pipe.fill(pin, a_consts, bt(C_BYTES, C_NW, 4096))
        for g in range(NG):
            pipe.drain(pout, a_act, bt(A_BYTES, A_OG + g * G * 2, G * 2))
            pipe.fill(pin, a_o, bt(D, g * G, G))
            pipe.fill(pin, a_act, bt(A_BYTES, A_Z + g * G * 4, G * 4))
        # 2. out-proj weights and the norm's x / w: independent, issue now
        tg_w, tg_y, tg_ln = TaskGroup(), TaskGroup(), TaskGroup()
        for c in range(N_CORES):
            w_prods[c].fill(a_w, tap=bt(WOUT_BYTES, c * OUT_PC * BAND_BYTES, OUT_PC * BAND_BYTES), wait=True, group=tg_w)
            y_conss[c].drain(a_act, tap=bt(A_BYTES, A_OUT + c * OUT_PC * BAND_ROWS * 4, OUT_PC * BAND_ROWS * 4), wait=True, group=tg_y)
        lni.fill(a_xres, tap=bt(HID, 0, HID), wait=True, group=tg_ln)
        lni.fill(a_consts, tap=bt(C_BYTES, C_POSTLN, 4096), wait=True, group=tg_ln)
        lno.drain(c_hdr, tap=bt(H_BYTES, H_XRES, 8192), wait=True, group=tg_ln)
        lno.drain(c_hdr, tap=bt(H_BYTES, H_XM, 4096), wait=True, group=tg_ln)
        pipe.finish()                                    # og is in DDR
        x_prod.fill(a_act, tap=bt(A_BYTES, A_OG, D * 2), wait=True, group=tg_y)
        tg_y.finish()                                    # out is in DDR
        # 3. residual + post-attention norm
        lni.fill(a_act, tap=bt(A_BYTES, A_OUT, HID * 4), wait=True, group=tg_ln)
        tg_ln.finish()
        tg_w.finish()

    rt = Runtime(sequence, [w_ty, o_ty, consts_ty, act_ty, xres_ty, hdr_ty,
                            of_pin.prod(tile=Tile(0, 0)), of_pout.cons(tile=Tile(0, 0)),
                            [of_w[c].prod(tile=Tile(c, 0)) for c in range(N_CORES)],
                            of_x.prod(tile=Tile(1, 0)),
                            [of_y[c].cons(tile=Tile(c, 0)) for c in range(N_CORES)],
                            of_lni.prod(tile=Tile(2, 0)), of_lno.cons(tile=Tile(2, 0))])
    return Program(iron.get_current_device(), rt, workers=workers).resolve_program()


DESIGN = lin_c
_src = b"".join(sorted(f.read_bytes() for f in POST.glob("*.cc")) + [(LN / "ln.cc").read_bytes(), (GEMV / "gemv_q4.h").read_bytes(),
                                                                      (HERE.parent.parent / "include" / "vecmath.h").read_bytes()])
SPECIALIZE = {"srchash": int(hashlib.sha1(_src).hexdigest()[:8], 16)}
