r"""lin_a: the front half of a linear-attention decode layer as ONE dispatch
(phase 2 item 1, design A1 of .claude/plans/open-kernels-phase2-fused-linear-layer.md):

    ln (layer-entry RMSNorm, no residual)  ->  gemv qkv | gemv z  ->  glue

Replaces 4 dispatches over 4 xclbin contexts plus a host round trip (`dump xn`
/ `load side`). The stages hand over through DDR (`act`): every fill that
reads a stage's output is issued after `dma_wait` on the drain that wrote it
(the command processor executes the sequence in order); everything that does
not depend on a previous stage (weight streams, constants) is issued early.
No kernel body changes: ln_nr.cc is ln.cc minus the add, the GEMV cores run
gemv_q4's entry points over qkv's 16 bands then z's 8 bands per core with x
broadcast once, the glue is dn_glue's core verbatim with its xn element
filled from `act` instead of the side blob.

Shim budget (2 fills + 2 drains per column; the reason this is one context):
  col 0: w0 + ln in | y0 + ln out      col 2: w2 + glue side | y2 + glue out
  col 1: w1 + x     | y1               col 3: w3 + glue act  | y3
  col 4-7: w | y

Args (see layout.py):
  w      u8[POOL_BYTES]  the layer pool (qkv at POOL_QKV, z at POOL_Z), or any BO with those offsets
  xres   f32[2048]       the layer's input residual
  consts u8[C_BYTES]     [lnw | Wa Wb small convw | nw | postln]
  state  bf16[3*8192]    conv state, updated IN PLACE
  act    u8[A_BYTES]     scratch: xn, qkv, z written here
  vec    f32[32*512]     out: per-head records for designs/deltanet
Build (WSL): python build_design.py designs/lin_layer/lin_a.py designs/lin_layer/build_a
"""

from __future__ import annotations

import hashlib
import sys
from pathlib import Path

import numpy as np
from ml_dtypes import bfloat16

import aie.iron as iron
from aie.iron import Buffer, CompileTime, In, InOut, ObjectFifo, Out, Program, Runtime, TaskGroup, Worker
from aie.iron.controlflow import range_
from aie.iron.device import Tile
from aie.iron.kernel import ExternalFunction
from aie.helpers.taplib import TensorAccessPattern

HERE = Path(__file__).parent
GEMV = HERE.parent / "gemv_q4"
GLUE = HERE.parent / "dn_glue"
sys.path.insert(0, str(HERE.parent.parent))
sys.path.insert(0, str(HERE))
from ironutil import Pipeline, include_dirs  # noqa: E402
from layout import (A_BYTES, A_QKV, A_XN, A_Z, C_BYTES, C_LNW, GLUE_SIDE_BYTES, GLUE_SIDE_OFF,  # noqa: E402
                    POOL_BYTES, POOL_QKV, POOL_Z)

HID = 2048
# gemv_q4, standard layout (RS=2): 64-row bands of K/128 = 16 chunks, 4 chunks per call
TILE_BYTES, PER_CALL, PER_BAND, BAND_ROWS = 5120, 4, 16, 64
BAND_BYTES = PER_BAND * TILE_BYTES            # 81920
CALL_BYTES = PER_CALL * TILE_BYTES
N_CORES = 8
QKV_PC = 8192 // BAND_ROWS // N_CORES         # 16 bands per core
Z_PC = 4096 // BAND_ROWS // N_CORES           # 8
# dn_glue
NCH, NHEAD = 8192, 32
TILE, NT = 1024, 8
SIDE_ELEM, ACT_ELEM, AB_ELEMS = 4096, 2048, 32


def bt(total: int, off: int, n: int) -> TensorAccessPattern:
    return TensorAccessPattern((1, total), off, [1, 1, 1, n], [0, 0, 0, 1])


def rows3(t: int) -> TensorAccessPattern:
    """Tile t (1024 bf16) of each of the 3 conv-state rows."""
    return TensorAccessPattern((3, NCH), t * TILE, [1, 1, 3, TILE], [0, 0, NCH, 1])


@iron.jit(aiecc_flags=["--alloc-scheme=basic-sequential"])
def lin_a(w: In, xres: In, consts: In, state: InOut, act: Out, vec: Out, *, srchash: CompileTime[int] = 0):
    u8_4k = np.ndarray[(4096,), np.dtype[np.uint8]]
    u8_2k = np.ndarray[(ACT_ELEM,), np.dtype[np.uint8]]
    w_ty = np.ndarray[(POOL_BYTES,), np.dtype[np.uint8]]
    xres_ty = np.ndarray[(HID,), np.dtype[np.float32]]
    consts_ty = np.ndarray[(C_BYTES,), np.dtype[np.uint8]]
    state_ty = np.ndarray[(3 * NCH,), np.dtype[bfloat16]]
    act_ty = np.ndarray[(A_BYTES,), np.dtype[np.uint8]]
    vec_ty = np.ndarray[(NHEAD * 512,), np.dtype[np.float32]]
    elem_ty = np.ndarray[(CALL_BYTES,), np.dtype[np.uint8]]
    x_ty = np.ndarray[(HID,), np.dtype[bfloat16]]
    tab_ty = np.ndarray[(2 * HID + HID // 4,), np.dtype[np.uint8]]   # gemv_q4_tab_bytes(2048)
    band_ty = np.ndarray[(BAND_ROWS,), np.dtype[np.float32]]
    f32 = np.ndarray[(32,), np.dtype[np.float32]]
    fqk = np.ndarray[(4096,), np.dtype[np.float32]]
    fvt = np.ndarray[(TILE,), np.dtype[np.float32]]
    fxn = np.ndarray[(HID,), np.dtype[bfloat16]]

    inc = include_dirs() + [str(GEMV), str(GLUE)]
    # ---- kernels
    ln_fn = ExternalFunction("ln_nr", source_file=str(HERE / "ln_nr.cc"), arg_types=[u8_4k] * 4, include_dirs=inc)
    ks = []
    for i in range(PER_BAND // PER_CALL):
        src = GEMV / f"gemv_q4_p{PER_CALL}b{PER_BAND}r2_k{i}.cc"
        assert src.is_file(), f"{src} (generated by gemv_q4.py)"
        ks.append(ExternalFunction(src.stem, source_file=str(src), arg_types=[elem_ty, tab_ty, band_ty], include_dirs=inc))
    prep = ExternalFunction("gemv_q4_prep_k2048", source_file=str(GEMV / "gemv_q4_prep_k2048.cc"),
                            arg_types=[x_ty, tab_ty], include_dirs=inc)
    f_ab = ExternalFunction("glue_ab", source_file=str(GLUE / "glue_ab.cc"), arg_types=[u8_4k, fxn, f32, np.int32], include_dirs=inc)
    f_small = ExternalFunction("glue_small_fn", source_file=str(GLUE / "glue_small.cc"), arg_types=[u8_4k, f32, f32, f32, f32], include_dirs=inc)
    f_conv = ExternalFunction("glue_conv", source_file=str(GLUE / "glue_conv.cc"),
                              arg_types=[u8_2k, u8_2k, u8_2k, u8_2k, u8_2k, u8_4k, u8_4k, u8_2k, u8_2k, u8_2k, fqk, fvt, np.int32, np.int32],
                              include_dirs=inc)
    f_emit = ExternalFunction("glue_emit_fn", source_file=str(GLUE / "glue_emit.cc"), arg_types=[fqk, fvt, f32, f32, u8_2k, np.int32, np.int32], include_dirs=inc)
    f_copy = ExternalFunction("glue_copy_xn", source_file=str(GLUE / "glue_copy.cc"), arg_types=[u8_4k, fxn], include_dirs=inc)

    # ---- fifos
    of_lni = ObjectFifo(u8_4k, name="lni", depth=3)      # [x0 x1 | w]
    of_lno = ObjectFifo(u8_4k, name="lno", depth=1)      # [xn]
    of_w = [ObjectFifo(elem_ty, name=f"w{c}", depth=2) for c in range(N_CORES)]
    of_y = [ObjectFifo(band_ty, name=f"y{c}", depth=2) for c in range(N_CORES)]
    of_x = ObjectFifo(x_ty, name="x", depth=1)
    of_side = ObjectFifo(u8_4k, name="side", depth=2)
    of_act = ObjectFifo(u8_2k, name="gact", depth=5)
    of_out = ObjectFifo(u8_2k, name="gout", depth=3)

    # ---- cores
    def ln_body(ain, aout, f):
        e = ain.acquire(3)
        o = aout.acquire(1)
        f(e[0], e[1], e[2], o)
        aout.release(1)
        ain.release(3)

    def gemv_body(win, xin, yout, tab, fprep, *fns):
        xe = xin.acquire(1)
        fprep(xe, tab)                            # block-quantise x once (gemv_q4.h)
        for _ in range_(QKV_PC + Z_PC):           # qkv's bands then z's: same K, same entry points
            ye = yout.acquire(1)
            for fn in fns:
                we = win.acquire(1)
                fn(we, tab, ye)
                win.release(1)
            yout.release(1)
        xin.release(1)

    def glue_body(sin, ain, oout, acc_a, acc_b, decay, beta, qk, vt, xn, fab, fsmall, fconv, femit, fcopy):
        e0 = sin.acquire(1)
        fcopy(e0, xn)
        sin.release(1)
        for acc in (acc_a, acc_b):
            for tile in range_(AB_ELEMS):
                ww = sin.acquire(1)
                fab(ww, xn, acc, tile)
                sin.release(1)
        sm = sin.acquire(1)
        fsmall(sm, acc_a, acc_b, decay, beta)
        sin.release(1)
        for base in (0, 4):
            for t in range_(4):
                ww = sin.acquire(2)
                e = ain.acquire(5)
                o = oout.acquire(3)
                fconv(e[0], e[1], e[2], e[3], e[4], ww[0], ww[1], o[0], o[1], o[2], qk, vt, t, base)
                oout.release(3)
                ain.release(5)
                sin.release(2)
                if base == 4:
                    for i in range_(8):
                        r = oout.acquire(1)
                        femit(qk, vt, decay, beta, r, t, i)
                        oout.release(1)

    workers = [Worker(ln_body, fn_args=[of_lni.cons(), of_lno.prod(), ln_fn], tile=Tile(0, 3), stack_size=0x1800)]
    for c in range(N_CORES):
        workers.append(Worker(gemv_body, fn_args=[of_w[c].cons(), of_x.cons(), of_y[c].prod(),
                                                  Buffer(tab_ty, name=f"tab{c}"), prep, *ks],
                              tile=Tile(c, 2), stack_size=0x1000))
    workers.append(Worker(glue_body,
                          fn_args=[of_side.cons(), of_act.cons(), of_out.prod(),
                                   Buffer(f32, name="acc_a"), Buffer(f32, name="acc_b"), Buffer(f32, name="decay"),
                                   Buffer(f32, name="beta"), Buffer(fqk, name="qk"), Buffer(fvt, name="vt"), Buffer(fxn, name="xnb"),
                                   f_ab, f_small, f_conv, f_emit, f_copy],
                          tile=Tile(2, 3), stack_size=0x1800))

    # ---- host sequence
    def sequence(a_w, a_xres, a_consts, a_state, a_act, c_vec, lni, lno, w_prods, x_prod, y_conss, side_p, act_p, out_c):
        # 1. layer-entry norm: xn -> act[A_XN]
        tg_ln = TaskGroup()
        lni.fill(a_xres, tap=bt(HID, 0, HID), wait=True, group=tg_ln)
        lni.fill(a_consts, tap=bt(C_BYTES, C_LNW, 4096), wait=True, group=tg_ln)
        lno.drain(a_act, tap=bt(A_BYTES, A_XN, 4096), wait=True, group=tg_ln)
        # 2. qkv | z GEMV: weights stream now (independent of xn), x after the norm
        tg_w, tg_y = TaskGroup(), TaskGroup()
        for c in range(N_CORES):
            w_prods[c].fill(a_w, tap=bt(POOL_BYTES, POOL_QKV + c * QKV_PC * BAND_BYTES, QKV_PC * BAND_BYTES), wait=True, group=tg_w)
            w_prods[c].fill(a_w, tap=bt(POOL_BYTES, POOL_Z + c * Z_PC * BAND_BYTES, Z_PC * BAND_BYTES), wait=True, group=tg_w)
            y_conss[c].drain(a_act, tap=bt(A_BYTES, A_QKV + c * QKV_PC * BAND_ROWS * 4, QKV_PC * BAND_ROWS * 4), wait=True, group=tg_y)
            y_conss[c].drain(a_act, tap=bt(A_BYTES, A_Z + c * Z_PC * BAND_ROWS * 4, Z_PC * BAND_ROWS * 4), wait=True, group=tg_y)
        tg_ln.finish()                                   # xn is in DDR
        x_prod.fill(a_act, tap=bt(A_BYTES, A_XN, 4096), wait=True, group=tg_y)
        # glue side stream = [xn | Wa Wb small convw] (also only needs xn)
        tg_s = TaskGroup()
        side_p.fill(a_act, tap=bt(A_BYTES, A_XN, 4096), wait=True, group=tg_s)
        side_p.fill(a_consts, tap=bt(C_BYTES, GLUE_SIDE_OFF, GLUE_SIDE_BYTES), wait=True, group=tg_s)
        tg_y.finish()                                    # qkv, z are in DDR
        # 3. glue: conv state updated in place, DeltaNet records out
        pipe = Pipeline(3)
        for t in range(NT):
            pipe.drain(out_c, a_state, rows3(t))
            if t >= 4:
                pipe.drain(out_c, c_vec, bt(NHEAD * 512, (t - 4) * 8 * 512, 8 * 512))
            pipe.fill(act_p, a_act, bt(A_BYTES, A_QKV + t * TILE * 4, TILE * 4))
            pipe.fill(act_p, a_state, rows3(t))
        pipe.finish()
        tg_s.finish()
        tg_w.finish()

    rt = Runtime(sequence, [w_ty, xres_ty, consts_ty, state_ty, act_ty, vec_ty,
                            of_lni.prod(tile=Tile(0, 0)), of_lno.cons(tile=Tile(0, 0)),
                            [of_w[c].prod(tile=Tile(c, 0)) for c in range(N_CORES)],
                            of_x.prod(tile=Tile(1, 0)),
                            [of_y[c].cons(tile=Tile(c, 0)) for c in range(N_CORES)],
                            of_side.prod(tile=Tile(2, 0)), of_act.prod(tile=Tile(3, 0)), of_out.cons(tile=Tile(2, 0))])
    return Program(iron.get_current_device(), rt, workers=workers).resolve_program()


DESIGN = lin_a
_src = b"".join(sorted(f.read_bytes() for f in HERE.glob("*.cc")) + sorted(f.read_bytes() for f in GLUE.glob("*.cc"))
                + sorted(f.read_bytes() for f in GLUE.glob("*.h")) + [(GEMV / "gemv_q4.h").read_bytes(),
                                                                       (HERE.parent.parent / "include" / "vecmath.h").read_bytes()])
SPECIALIZE = {"srchash": int(hashlib.sha1(_src).hexdigest()[:8], 16)}
