//===- gelu_poly.cc -----------------------------------------*- C++ -*-===//
//
// NpuEmbeddings -- GELU with no transcendental call.
// SPDX-License-Identifier: MIT
//
// WHY
// ---
// tasks/0014 isolated the error in the shipped GELU to `aie::tanh` itself,
// which is only ~1% accurate on this part. Feeding it fp32 does not help --
// measured 1.316e-02 with a fully fp32 polynomial around it, against a bf16
// output floor of 2.465e-03. So GELU has to be evaluated without it.
//
// THE FORM
// --------
//   GELU(-x) = -x*Phi(-x) = -x*(1 - Phi(x)) = GELU(x) - x
//
// so  c(x) = GELU(x) - max(x,0)  satisfies  c(-x) = c(x): it is EVEN, and it
// decays like a Gaussian (c(4) = -1.3e-04, c(5) = -2.9e-06). Therefore
//
//   GELU(x) = max(x, 0) + c(min(|x|, R))
//
// and clamping at R costs nothing because c is already ~0 there -- no branch,
// no select, no masking. Degree 8 with R = 4 lands at 2.494e-03 on the real
// L0.ffn_up activations, which is 1.01x the bf16 floor and 5.3x better than
// aie::tanh. Coefficients fitted at Chebyshev nodes by
// experiments/m5-eltwise/design_gelu_poly.py.
//
// Every operation below is a native vector op: abs, min, max, mul, add. No
// division, no elementary-function library. research/notes/0001 forbids scalar
// float in a kernel body (1,617x measured), and nothing here is scalar.
//
// tasks/0091 (register T7/T8): the bf16<->fp32 widen/narrow used to go through
// `aie::mul(v, 1.0f).to_vector<T>()`, which tasks/0045 measured as an
// EMULATED fp32 multiply -- real instructions for a value-preserving cast.
// Fixed here with `accum<accfloat,16>::from_vector`/`to_vector<T>()`, which
// rides the native widen-on-load / narrow-on-store instructions instead (0
// `vmul.f`/`vadd.f` in isolated probes). T8 added `gelu_poly_impl_deg7`: one
// fewer Horner step than the shipped degree-8, refit (not truncated) on the
// same Chebyshev nodes, kept as a separate entry point rather than a default
// change -- see the function's own comment for the accuracy numbers.

#include "aie_kernel_utils.h"
#include <aie_api/aie.hpp>
#include <stdint.h>

using namespace aie;

// c(u) on [0, 4], Horner order, highest power first.
// Generated by design_gelu_poly.py; see artifacts/gelu_poly.json.
#define GELU_R 4.0f
#define GELU_C0 -7.2340282171e-05f
#define GELU_C1 1.8179518005e-03f
#define GELU_C2 -1.7707383379e-02f
#define GELU_C3 8.4577147641e-02f
#define GELU_C4 -1.9228671834e-01f
#define GELU_C5 9.8431124458e-02f
#define GELU_C6 3.6137852062e-01f
#define GELU_C7 -4.9454128936e-01f
#define GELU_C8 -1.3007010117e-04f

void gelu_poly_impl(bfloat16 *restrict input_vector,
                    bfloat16 *restrict output_vector,
                    const int32_t vector_size) {
  event0();

  auto it_in = aie::begin_restrict_vector<16>((bfloat16 *)input_vector);
  auto it_out = aie::begin_restrict_vector<16>((bfloat16 *)output_vector);

  const aie::vector<float, 16> vzero = aie::broadcast<float, 16>(0.0f);
  const aie::vector<float, 16> vR = aie::broadcast<float, 16>(GELU_R);
  const aie::vector<float, 16> k0 = aie::broadcast<float, 16>(GELU_C0);
  const aie::vector<float, 16> k1 = aie::broadcast<float, 16>(GELU_C1);
  const aie::vector<float, 16> k2 = aie::broadcast<float, 16>(GELU_C2);
  const aie::vector<float, 16> k3 = aie::broadcast<float, 16>(GELU_C3);
  const aie::vector<float, 16> k4 = aie::broadcast<float, 16>(GELU_C4);
  const aie::vector<float, 16> k5 = aie::broadcast<float, 16>(GELU_C5);
  const aie::vector<float, 16> k6 = aie::broadcast<float, 16>(GELU_C6);
  const aie::vector<float, 16> k7 = aie::broadcast<float, 16>(GELU_C7);
  const aie::vector<float, 16> k8 = aie::broadcast<float, 16>(GELU_C8);

  // FOUR independent 16-lane chains per iteration, interleaved.
  //
  // Horner is strictly serial: nine dependent mul->srs pairs, and each has real
  // latency, so a single chain leaves the pipeline mostly empty. Measured at
  // batch 64 the one-chain version ran 6.3 M elements in 16.4 ms -- ~334 cycles
  // per 16-lane iteration, against maybe 30 cycles of actual work.
  //
  // It is not DMA: a passthrough moving the SAME 25.2 MB over the SAME two
  // columns takes 524 us, so the array can feed this 31x faster than the
  // polynomial consumed it (tasks/0026). Interleaving four chains gives the
  // compiler four independent streams to fill the pipeline with.
  //
  // Numerics are UNCHANGED: each chain performs the same operations in the same
  // order on its own data, so the result is bit-identical to one chain.

#define GELU_HORNER(K)                                                        \
  p0 = aie::add(aie::mul(p0, u0).to_vector<float>(), K);                       \
  p1 = aie::add(aie::mul(p1, u1).to_vector<float>(), K);                       \
  p2 = aie::add(aie::mul(p2, u2).to_vector<float>(), K);                       \
  p3 = aie::add(aie::mul(p3, u3).to_vector<float>(), K);

  AIE_PREPARE_FOR_PIPELINING
  AIE_LOOP_MIN_ITERATION_COUNT(4)
  for (int i = 0; i < vector_size; i += 64) {
    // Widen bf16 -> fp32 via accum::from_vector, NOT the multiply-by-1.0f
    // idiom the comment here used to recommend (tasks/0045, tasks/0091 T7).
    // The multiply form is emulated on aie2p -- 0091 measured it at 4
    // `vmul.f` for 64 elements with zero real arithmetic, isolated in
    // scratchpad probes (widen_probe.cc) compiled the same way as this file.
    // `accum<accfloat,16>::from_vector` on a bf16 vector compiles to
    // `vlda.conv.fp32.bf16` -- a load-with-conversion, 0 vmul.f/vadd.f --
    // because the AIE API's UPSHIFT path (aie_api/detail/aie2p/accum.hpp)
    // recognises bf16 -> accfloat as a native widen, not a value-changing
    // multiply.
    aie::accum<accfloat, 16> ax0, ax1, ax2, ax3;
    ax0.from_vector(*it_in++);
    ax1.from_vector(*it_in++);
    ax2.from_vector(*it_in++);
    ax3.from_vector(*it_in++);
    aie::vector<float, 16> x0 = ax0.to_vector<float>();
    aie::vector<float, 16> x1 = ax1.to_vector<float>();
    aie::vector<float, 16> x2 = ax2.to_vector<float>();
    aie::vector<float, 16> x3 = ax3.to_vector<float>();

    aie::vector<float, 16> u0 = aie::min(aie::abs(x0), vR);
    aie::vector<float, 16> u1 = aie::min(aie::abs(x1), vR);
    aie::vector<float, 16> u2 = aie::min(aie::abs(x2), vR);
    aie::vector<float, 16> u3 = aie::min(aie::abs(x3), vR);

    // Horner, fp32 throughout, rounded exactly once on the store below.
    aie::vector<float, 16> p0 = k0, p1 = k0, p2 = k0, p3 = k0;
    GELU_HORNER(k1)
    GELU_HORNER(k2)
    GELU_HORNER(k3)
    GELU_HORNER(k4)
    GELU_HORNER(k5)
    GELU_HORNER(k6)
    GELU_HORNER(k7)
    GELU_HORNER(k8)

    // Narrow fp32 -> bf16 via accum::from_vector (tasks/0045's finding,
    // applied here per tasks/0091 T7 -- this file was 0045's own "worth
    // following up separately" note). `to_vector<bfloat16>()` on an
    // accfloat accumulator rides the store's `vst.conv.bf16.fp32`, free.
    aie::accum<accfloat, 16> ao0, ao1, ao2, ao3;
    ao0.from_vector(aie::add(aie::max(x0, vzero), p0));
    ao1.from_vector(aie::add(aie::max(x1, vzero), p1));
    ao2.from_vector(aie::add(aie::max(x2, vzero), p2));
    ao3.from_vector(aie::add(aie::max(x3, vzero), p3));
    *it_out++ = ao0.to_vector<bfloat16>();
    *it_out++ = ao1.to_vector<bfloat16>();
    *it_out++ = ao2.to_vector<bfloat16>();
    *it_out++ = ao3.to_vector<bfloat16>();
  }
#undef GELU_HORNER

  event1();
  return;
}

#ifndef NPUE_ELTWISE_IMPL_ONLY
void gelu_poly_impl_deg2(bfloat16 *restrict input_vector,
                    bfloat16 *restrict output_vector,
                    const int32_t vector_size) {
  event0();

  auto it_in = aie::begin_restrict_vector<16>((bfloat16 *)input_vector);
  auto it_out = aie::begin_restrict_vector<16>((bfloat16 *)output_vector);

  const aie::vector<float, 16> vzero = aie::broadcast<float, 16>(0.0f);
  const aie::vector<float, 16> vR = aie::broadcast<float, 16>(GELU_R);
  const aie::vector<float, 16> k0 = aie::broadcast<float, 16>(GELU_C0);
  const aie::vector<float, 16> k1 = aie::broadcast<float, 16>(GELU_C1);
  const aie::vector<float, 16> k2 = aie::broadcast<float, 16>(GELU_C2);
  const aie::vector<float, 16> k3 = aie::broadcast<float, 16>(GELU_C3);
  const aie::vector<float, 16> k4 = aie::broadcast<float, 16>(GELU_C4);
  const aie::vector<float, 16> k5 = aie::broadcast<float, 16>(GELU_C5);
  const aie::vector<float, 16> k6 = aie::broadcast<float, 16>(GELU_C6);
  const aie::vector<float, 16> k7 = aie::broadcast<float, 16>(GELU_C7);
  const aie::vector<float, 16> k8 = aie::broadcast<float, 16>(GELU_C8);

  // FOUR independent 16-lane chains per iteration, interleaved.
  //
  // Horner is strictly serial: nine dependent mul->srs pairs, and each has real
  // latency, so a single chain leaves the pipeline mostly empty. Measured at
  // batch 64 the one-chain version ran 6.3 M elements in 16.4 ms -- ~334 cycles
  // per 16-lane iteration, against maybe 30 cycles of actual work.
  //
  // It is not DMA: a passthrough moving the SAME 25.2 MB over the SAME two
  // columns takes 524 us, so the array can feed this 31x faster than the
  // polynomial consumed it (tasks/0026). Interleaving four chains gives the
  // compiler four independent streams to fill the pipeline with.
  //
  // Numerics are UNCHANGED: each chain performs the same operations in the same
  // order on its own data, so the result is bit-identical to one chain.

#define GELU_HORNER(K)                                                        \
  p0 = aie::add(aie::mul(p0, u0).to_vector<float>(), K);                       \
  p1 = aie::add(aie::mul(p1, u1).to_vector<float>(), K);                       \
  p2 = aie::add(aie::mul(p2, u2).to_vector<float>(), K);                       \
  p3 = aie::add(aie::mul(p3, u3).to_vector<float>(), K);

  AIE_PREPARE_FOR_PIPELINING
  AIE_LOOP_MIN_ITERATION_COUNT(4)
  for (int i = 0; i < vector_size; i += 64) {
    // Widen bf16 -> fp32 via accum::from_vector, NOT the multiply-by-1.0f
    // idiom the comment here used to recommend (tasks/0045, tasks/0091 T7).
    // The multiply form is emulated on aie2p -- 0091 measured it at 4
    // `vmul.f` for 64 elements with zero real arithmetic, isolated in
    // scratchpad probes (widen_probe.cc) compiled the same way as this file.
    // `accum<accfloat,16>::from_vector` on a bf16 vector compiles to
    // `vlda.conv.fp32.bf16` -- a load-with-conversion, 0 vmul.f/vadd.f --
    // because the AIE API's UPSHIFT path (aie_api/detail/aie2p/accum.hpp)
    // recognises bf16 -> accfloat as a native widen, not a value-changing
    // multiply.
    aie::accum<accfloat, 16> ax0, ax1, ax2, ax3;
    ax0.from_vector(*it_in++);
    ax1.from_vector(*it_in++);
    ax2.from_vector(*it_in++);
    ax3.from_vector(*it_in++);
    aie::vector<float, 16> x0 = ax0.to_vector<float>();
    aie::vector<float, 16> x1 = ax1.to_vector<float>();
    aie::vector<float, 16> x2 = ax2.to_vector<float>();
    aie::vector<float, 16> x3 = ax3.to_vector<float>();

    aie::vector<float, 16> u0 = aie::min(aie::abs(x0), vR);
    aie::vector<float, 16> u1 = aie::min(aie::abs(x1), vR);
    aie::vector<float, 16> u2 = aie::min(aie::abs(x2), vR);
    aie::vector<float, 16> u3 = aie::min(aie::abs(x3), vR);

    // TWO Horner steps instead of eight -- the whole point of the probe.
    aie::vector<float, 16> p0 = k0, p1 = k0, p2 = k0, p3 = k0;
    GELU_HORNER(k1)
    GELU_HORNER(k2)

    // Narrow fp32 -> bf16 via accum::from_vector (tasks/0045's finding,
    // applied here per tasks/0091 T7 -- this file was 0045's own "worth
    // following up separately" note). `to_vector<bfloat16>()` on an
    // accfloat accumulator rides the store's `vst.conv.bf16.fp32`, free.
    aie::accum<accfloat, 16> ao0, ao1, ao2, ao3;
    ao0.from_vector(aie::add(aie::max(x0, vzero), p0));
    ao1.from_vector(aie::add(aie::max(x1, vzero), p1));
    ao2.from_vector(aie::add(aie::max(x2, vzero), p2));
    ao3.from_vector(aie::add(aie::max(x3, vzero), p3));
    *it_out++ = ao0.to_vector<bfloat16>();
    *it_out++ = ao1.to_vector<bfloat16>();
    *it_out++ = ao2.to_vector<bfloat16>();
    *it_out++ = ao3.to_vector<bfloat16>();
  }
#undef GELU_HORNER

  event1();
  return;
}

// tasks/0091 T8: degree 7, one Horner step fewer than the shipped degree-8
// above. NOT the degree-8 fit with its top term dropped -- a fresh
// least-squares refit at degree 7 on the SAME Chebyshev nodes
// (design_gelu_poly.py's own fit(), R=4), because truncating an existing
// fit's leading term is not the best degree-7 polynomial on this range.
//
// Correctness check (research/notes/0007 SS3.2 reproduced numerically in
// tasks/0091, numpy only, real L0.ffn_up activations, full pipeline
// including the bf16 output round -- the SAME `rel_fro` metric the header
// above quotes 2.494e-03 for degree 8):
//
//   degree 7:  rel_fro = 2.503e-03  (1.016x the bf16 floor of 2.465e-03)
//   degree 8:  rel_fro = 2.494e-03  (1.012x the bf16 floor)  <- matches the
//                                      header's own number exactly
//
// Note 0007's table (7.324e-03 / 5.913e-04 / 3.613e-04 / "4.2x inside the
// floor") is NOT this quantity -- it is smaller and does not appear to
// include the bf16 output rounding step, so it understates how close
// degree 7 already sits to degree 8 once the real pipeline is measured.
// See tasks/0091/TASK.md for the full reproduction and the two numbers'
// reconciliation attempt. The DIRECTION 0007 argued for still holds --
// degree 7 costs a negligible 0.36% relative increase in end-to-end error
// over degree 8, both comfortably usable -- so this is kept as a real,
// selectable variant rather than a replacement for the shipped degree-8.
#define GELU7_C0 6.6050728574e-04f
#define GELU7_C1 -1.0183994033e-02f
#define GELU7_C2 5.9113368317e-02f
#define GELU7_C3 -1.4454213211e-01f
#define GELU7_C4 4.9818454839e-02f
#define GELU7_C5 3.8568485542e-01f
#define GELU7_C6 -4.9917106742e-01f
#define GELU7_C7 1.4610463161e-05f

void gelu_poly_impl_deg7(bfloat16 *restrict input_vector,
                         bfloat16 *restrict output_vector,
                         const int32_t vector_size) {
  event0();

  auto it_in = aie::begin_restrict_vector<16>((bfloat16 *)input_vector);
  auto it_out = aie::begin_restrict_vector<16>((bfloat16 *)output_vector);

  const aie::vector<float, 16> vzero = aie::broadcast<float, 16>(0.0f);
  const aie::vector<float, 16> vR = aie::broadcast<float, 16>(GELU_R);
  const aie::vector<float, 16> k0 = aie::broadcast<float, 16>(GELU7_C0);
  const aie::vector<float, 16> k1 = aie::broadcast<float, 16>(GELU7_C1);
  const aie::vector<float, 16> k2 = aie::broadcast<float, 16>(GELU7_C2);
  const aie::vector<float, 16> k3 = aie::broadcast<float, 16>(GELU7_C3);
  const aie::vector<float, 16> k4 = aie::broadcast<float, 16>(GELU7_C4);
  const aie::vector<float, 16> k5 = aie::broadcast<float, 16>(GELU7_C5);
  const aie::vector<float, 16> k6 = aie::broadcast<float, 16>(GELU7_C6);
  const aie::vector<float, 16> k7 = aie::broadcast<float, 16>(GELU7_C7);

#define GELU7_HORNER(K)                                                      \
  p0 = aie::add(aie::mul(p0, u0).to_vector<float>(), K);                     \
  p1 = aie::add(aie::mul(p1, u1).to_vector<float>(), K);                     \
  p2 = aie::add(aie::mul(p2, u2).to_vector<float>(), K);                     \
  p3 = aie::add(aie::mul(p3, u3).to_vector<float>(), K);

  AIE_PREPARE_FOR_PIPELINING
  AIE_LOOP_MIN_ITERATION_COUNT(4)
  for (int i = 0; i < vector_size; i += 64) {
    aie::accum<accfloat, 16> ax0, ax1, ax2, ax3;
    ax0.from_vector(*it_in++);
    ax1.from_vector(*it_in++);
    ax2.from_vector(*it_in++);
    ax3.from_vector(*it_in++);
    aie::vector<float, 16> x0 = ax0.to_vector<float>();
    aie::vector<float, 16> x1 = ax1.to_vector<float>();
    aie::vector<float, 16> x2 = ax2.to_vector<float>();
    aie::vector<float, 16> x3 = ax3.to_vector<float>();

    aie::vector<float, 16> u0 = aie::min(aie::abs(x0), vR);
    aie::vector<float, 16> u1 = aie::min(aie::abs(x1), vR);
    aie::vector<float, 16> u2 = aie::min(aie::abs(x2), vR);
    aie::vector<float, 16> u3 = aie::min(aie::abs(x3), vR);

    // SEVEN Horner steps: k0 is the leading coefficient, k1..k7 fold in below
    // -- one fewer than the shipped degree-8's k1..k8.
    aie::vector<float, 16> p0 = k0, p1 = k0, p2 = k0, p3 = k0;
    GELU7_HORNER(k1)
    GELU7_HORNER(k2)
    GELU7_HORNER(k3)
    GELU7_HORNER(k4)
    GELU7_HORNER(k5)
    GELU7_HORNER(k6)
    GELU7_HORNER(k7)

    aie::accum<accfloat, 16> ao0, ao1, ao2, ao3;
    ao0.from_vector(aie::add(aie::max(x0, vzero), p0));
    ao1.from_vector(aie::add(aie::max(x1, vzero), p1));
    ao2.from_vector(aie::add(aie::max(x2, vzero), p2));
    ao3.from_vector(aie::add(aie::max(x3, vzero), p3));
    *it_out++ = ao0.to_vector<bfloat16>();
    *it_out++ = ao1.to_vector<bfloat16>();
    *it_out++ = ao2.to_vector<bfloat16>();
    *it_out++ = ao3.to_vector<bfloat16>();
  }
#undef GELU7_HORNER

  event1();
  return;
}

#endif // NPUE_ELTWISE_IMPL_ONLY

// GELU as a GEMM epilogue (expert review section 2, notes/0005): applied to
// the fp32 output tile IN L1, before it is released to the C fifo. No
// bf16 widen/narrow at all -- the tile is already fp32 -- and no extra DMA,
// no extra dispatch, no design switch. The bias is not added here: it rides
// in as an augmented K-block (A gets a ones column, B gets the bias row), so
// by the time this runs, elem_out already holds A@B + bias.
//
// Single Horner chain: the GEMM worker stack is 0xD00 and the 4-chain variant
// needs 0x2000 (measured the hard way, tasks/0026). One chain keeps 3 vectors
// live and fits. Interleaving can come later if the epilogue ever shows up in
// a trace.
#ifndef NPUE_ELTWISE_IMPL_ONLY
void gelu_poly_f32_epilogue(float *restrict inout, const int32_t n) {
  auto it = aie::begin_restrict_vector<16>(inout);
  auto ot = aie::begin_restrict_vector<16>(inout);
  const aie::vector<float, 16> vzero = aie::broadcast<float, 16>(0.0f);
  const aie::vector<float, 16> vR = aie::broadcast<float, 16>(GELU_R);
  const aie::vector<float, 16> c0 = aie::broadcast<float, 16>(GELU_C0);
  const aie::vector<float, 16> c1 = aie::broadcast<float, 16>(GELU_C1);
  const aie::vector<float, 16> c2 = aie::broadcast<float, 16>(GELU_C2);
  const aie::vector<float, 16> c3 = aie::broadcast<float, 16>(GELU_C3);
  const aie::vector<float, 16> c4 = aie::broadcast<float, 16>(GELU_C4);
  const aie::vector<float, 16> c5 = aie::broadcast<float, 16>(GELU_C5);
  const aie::vector<float, 16> c6 = aie::broadcast<float, 16>(GELU_C6);
  const aie::vector<float, 16> c7 = aie::broadcast<float, 16>(GELU_C7);
  const aie::vector<float, 16> c8 = aie::broadcast<float, 16>(GELU_C8);
  // FOUR interleaved chains, for the same reason as the standalone kernel:
  // a single Horner chain is latency bound (~9 dependent mul->srs pairs) and
  // measured 1.47x SLOWER fused than the separate pieces. Requires the worker
  // stack at 0x2000 -- 12 live vectors overrun 0xD00 and corrupt silently
  // (tasks/0026).
#define GELU_EPI_STEP(C)                                                        p0 = aie::add(aie::mul(p0, u0).to_vector<float>(), C);                         p1 = aie::add(aie::mul(p1, u1).to_vector<float>(), C);                         p2 = aie::add(aie::mul(p2, u2).to_vector<float>(), C);                         p3 = aie::add(aie::mul(p3, u3).to_vector<float>(), C);
  AIE_PREPARE_FOR_PIPELINING
  AIE_LOOP_MIN_ITERATION_COUNT(4)
  for (int i = 0; i < n; i += 64) {
    aie::vector<float, 16> x0 = *it++, x1 = *it++, x2 = *it++, x3 = *it++;
    aie::vector<float, 16> u0 = aie::min(aie::abs(x0), vR);
    aie::vector<float, 16> u1 = aie::min(aie::abs(x1), vR);
    aie::vector<float, 16> u2 = aie::min(aie::abs(x2), vR);
    aie::vector<float, 16> u3 = aie::min(aie::abs(x3), vR);
    aie::vector<float, 16> p0 = c0, p1 = c0, p2 = c0, p3 = c0;
    GELU_EPI_STEP(c1)
    GELU_EPI_STEP(c2)
    GELU_EPI_STEP(c3)
    GELU_EPI_STEP(c4)
    GELU_EPI_STEP(c5)
    GELU_EPI_STEP(c6)
    GELU_EPI_STEP(c7)
    GELU_EPI_STEP(c8)
    // fp32 in, fp32 out: the result of aie::add() below is ALREADY
    // aie::vector<float,16> -- no conversion of any kind is needed. The
    // multiply-by-1.0f-then-to_vector<float>() this replaced (tasks/0091 T7)
    // was not even doing a widen or a narrow; it routed a same-type value
    // through the emulated fp32 multiply for no reason, so this is a plain
    // deletion, not a from_vector/to_vector substitution.
    *ot++ = aie::add(aie::max(x0, vzero), p0);
    *ot++ = aie::add(aie::max(x1, vzero), p1);
    *ot++ = aie::add(aie::max(x2, vzero), p2);
    *ot++ = aie::add(aie::max(x3, vzero), p3);
  }
#undef GELU_EPI_STEP
}

#endif // NPUE_ELTWISE_IMPL_ONLY

extern "C" {

#ifndef NPUE_ELTWISE_IMPL_ONLY
void gelu_poly_bf16(bfloat16 *restrict input, bfloat16 *restrict output) {
  gelu_poly_impl(input, output, 1024);
}

// A 4096-element variant, because the tile size turned out to be the cost.
//
// At batch 64 GELU moved 25 MB per call in 16.5 ms -- 1.5 GB/s against the
// 33 GB/s tasks/0010 measured -- and 21.5 us per 1024-element tile against
// roughly 2 us of arithmetic. That is per-transaction overhead, not bandwidth
// and not compute, so the fix is fewer and larger transactions.
//
// L1 budget (trap 3): 2 fifos x depth 2 x 4096 x 2 B = 32 KB of 64 KB.
void gelu_poly_bf16_4k(bfloat16 *restrict input, bfloat16 *restrict output) {
  gelu_poly_impl(input, output, 4096);
}

// SPEED PROBE ONLY -- numerically wrong on purpose. Do not ship.
//
// GELU costs 9.4 ms where a passthrough moving the same bytes over the same
// columns costs 0.52 ms, so it is compute bound by 18x. This asks WHAT the
// compute is: same structure, same four interleaved chains, same bf16<->f32
// widen and narrow, but the Horner chain cut from 8 steps to 2.
//
//   time scales with degree  -> the srs chain is the cost, and Estrin or a
//                               lower degree is a real lever
//   time barely moves        -> the widen/narrow or loop overhead dominates and
//                               shortening the polynomial buys nothing
void gelu_probe_deg2_bf16(bfloat16 *restrict input, bfloat16 *restrict output) {
  gelu_poly_impl_deg2(input, output, 1024);
}

// tasks/0091 T8: NUMERICALLY CORRECT (unlike the deg2 probe above) --
// degree 7, refit, see gelu_poly_impl_deg7's own comment for the accuracy
// evidence. Not wired into any design; a real degree-7 entry point for
// whoever picks up eltwise-on-array next, per note 0007's own "worth taking
// when eltwise next runs on the array" verdict.
void gelu_poly_deg7_bf16(bfloat16 *restrict input, bfloat16 *restrict output) {
  gelu_poly_impl_deg7(input, output, 1024);
}

void gelu_epilogue_3072_f32(float *restrict inout) {
  gelu_poly_f32_epilogue(inout, 3072);
}

// NPUE-M10 (tasks/0054, T28 Del B / B1): bge-large's tile is (64,64,32) --
// tile_n=32, not 48 (0042: N in {1024,3072,4096} makes 48 illegal) -- so its
// ffn_up epilogue tile is m*n=2048, not 3072. Same loop body, same 4-chain
// structure, same 0x2000 stack requirement; only n changes.
void gelu_epilogue_2048_f32(float *restrict inout) {
  gelu_poly_f32_epilogue(inout, 2048);
}

// NPUE-M10 (tasks/0054, T28 Del B / B2): a SEPARATE-core GELU worker, unlike
// the in-place epilogue above which runs on the SAME core that produced the
// GEMM tile. This one has independent input/output ObjectFifos (the pipeline
// prototype's GELU core acquires a GEMM-produced tile from a mem-tile-fed
// consumer fifo and a fresh tile from its own producer fifo -- two different
// underlying buffers, not one), so it cannot mutate in place. Vectorised copy
// then the proven in-place polynomial -- no scalar float math (note 0001).
void gelu_epilogue_3072_f32_io(float *restrict in, float *restrict out) {
  auto it = aie::begin_restrict_vector<16>(in);
  auto ot = aie::begin_restrict_vector<16>(out);
  for (int i = 0; i < 3072; i += 16) {
    *ot++ = *it++;
  }
  gelu_poly_f32_epilogue(out, 3072);
}

// NPUE-M10 (tasks/0054, T28 Del B / B2 diagnostic): pure copy, no math at
// all -- isolates "did the cross-core hop deliver the right bytes" from "is
// the GELU math on this new two-arg kernel correct", when the pipeline
// probe's end-to-end rel_fro came out wrong (1.333) and finite.
void identity_copy_3072_f32(float *restrict in, float *restrict out) {
  auto it = aie::begin_restrict_vector<16>(in);
  auto ot = aie::begin_restrict_vector<16>(out);
  for (int i = 0; i < 3072; i += 16) {
    *ot++ = *it++;
  }
}

// NpuEmbeddings -- tasks/0057, T28 Del C: a plain 6144-element (2-tile) copy,
// used as the "gather-consumer" core's kernel in join_then_consume_probe.py
// -- isolates whether a mem-tile JOIN's own .cons() can be handed directly to
// a THIRD Worker (no second split()/forward() on the same object) from
// whether any real compute on the gathered data is correct.
void identity_copy_6144_f32(float *restrict in, float *restrict out) {
  auto it = aie::begin_restrict_vector<16>(in);
  auto ot = aie::begin_restrict_vector<16>(out);
  for (int i = 0; i < 6144; i += 16) {
    *ot++ = *it++;
  }
}

// NPUE-M11 (tasks/0061, T28 hierarchical merge): a GEMM-producer-core
// epilogue combining gelu_poly_f32_epilogue's math with narrow_f32_bf16.cc's
// accum::from_vector narrowing -- fp32 accumulator IN, GELU'd bf16 OUT, RNE
// rounded (aie::set_rounding(conv_even), same reasoning as narrow_f32_bf16.cc
// and the *_rne kernels: the AIE default `floor` is a systematic downward
// bias, trap 2b). Needed because the hierarchical-merge probe's SECOND-stage
// matmul takes bf16 "A" input, and the K-reduction that produced this value
// must finish in fp32 (trap 2) before any bf16 rounding happens -- this
// kernel is that one rounding, fused with GELU so it costs no extra pass.
void gelu_epilogue_3072_f32_to_bf16(float *restrict in,
                                    bfloat16 *restrict out) {
  aie::set_rounding(aie::rounding_mode::conv_even);
  auto it = aie::begin_restrict_vector<16>(in);
  auto ot = aie::begin_restrict_vector<16>(out);
  const aie::vector<float, 16> vzero = aie::broadcast<float, 16>(0.0f);
  const aie::vector<float, 16> vR = aie::broadcast<float, 16>(GELU_R);
  const aie::vector<float, 16> c0 = aie::broadcast<float, 16>(GELU_C0);
  const aie::vector<float, 16> c1 = aie::broadcast<float, 16>(GELU_C1);
  const aie::vector<float, 16> c2 = aie::broadcast<float, 16>(GELU_C2);
  const aie::vector<float, 16> c3 = aie::broadcast<float, 16>(GELU_C3);
  const aie::vector<float, 16> c4 = aie::broadcast<float, 16>(GELU_C4);
  const aie::vector<float, 16> c5 = aie::broadcast<float, 16>(GELU_C5);
  const aie::vector<float, 16> c6 = aie::broadcast<float, 16>(GELU_C6);
  const aie::vector<float, 16> c7 = aie::broadcast<float, 16>(GELU_C7);
  const aie::vector<float, 16> c8 = aie::broadcast<float, 16>(GELU_C8);
  for (int i = 0; i < 3072; i += 16) {
    aie::vector<float, 16> x = *it++;
    aie::vector<float, 16> u = aie::min(aie::abs(x), vR);
    aie::vector<float, 16> p = c0;
    p = aie::add(aie::mul(p, u).to_vector<float>(), c1);
    p = aie::add(aie::mul(p, u).to_vector<float>(), c2);
    p = aie::add(aie::mul(p, u).to_vector<float>(), c3);
    p = aie::add(aie::mul(p, u).to_vector<float>(), c4);
    p = aie::add(aie::mul(p, u).to_vector<float>(), c5);
    p = aie::add(aie::mul(p, u).to_vector<float>(), c6);
    p = aie::add(aie::mul(p, u).to_vector<float>(), c7);
    p = aie::add(aie::mul(p, u).to_vector<float>(), c8);
    aie::vector<float, 16> res = aie::add(aie::max(x, vzero), p);
    aie::accum<accfloat, 16> a;
    a.from_vector(res);
    *ot++ = a.to_vector<bfloat16>();
  }
}
#endif // NPUE_ELTWISE_IMPL_ONLY

} // extern "C"
