// GENERATED by gemv_q4.py: band chunk group 0 (chunks 0..3 of a 8-chunk band, row split 4).
#define GEMV_PER_CALL 4
#define GEMV_PER_BAND 8
#define GEMV_ROWSPLIT 4
#include "gemv_q4.h"

extern "C" {
GEMV_Q4_ENTRY(0)
}
