// GENERATED by gemv_q4.py: band chunk group 4 (chunks 16..19 of a 32-chunk band, row split 4).
#define GEMV_PER_CALL 4
#define GEMV_PER_BAND 32
#define GEMV_ROWSPLIT 4
#include "gemv_q4.h"

extern "C" {
GEMV_Q4_ENTRY(4)
}
