r"""q4_1 GEMV on the NPU from phlegm's pool-order chunks: y[N] = W[N,K] @ x[K].

Phase 1 of .claude/plans/open-kernels-feasibility.md: the first real compute
kernel, checked against the pool bytes FLM's closed kernel consumes (which are
themselves verified byte-exact against C:/caps captures in pools.rs).

Dataflow (after vegah/LLMNpuTest granite_gemv, Apache-2.0): n_cores workers,
each fed its contiguous slice of bands by its own shim stream in elements of
PER_CALL chunks (double-buffered in L1); x broadcast once through one fifo; each
core emits one result object (32*ROWSPLIT floats) per band.

Band law (see gemv_q4.h): ROWSPLIT = 2 for the standard std_perm regions
(qkv, z, shared experts, full-attn projections), 4 for routed-expert stripes
and down experts. Shape via env GEMV_N / GEMV_K / GEMV_RS / GEMV_CORES.

Build (WSL):  python build_design.py designs/gemv_q4/gemv_q4.py [out_dir]
Run (Win):    open-qwen-npu npu designs/gemv_q4/run_<region>.cfg   (see make_test.py)
"""

from __future__ import annotations

import hashlib
import os
from pathlib import Path

import numpy as np
from ml_dtypes import bfloat16

import aie.iron as iron
from aie.iron import Buffer, CompileTime, In, ObjectFifo, Out, Program, Runtime, TaskGroup, Worker
from aie.iron.controlflow import range_
from aie.iron.kernel import ExternalFunction
from aie.helpers.taplib import TensorAccessPattern, TensorTiler2D
from aie.utils import config

HERE = Path(__file__).parent

TILE_BYTES = 5120

# ---- the shape this build is specialised to; default = L0 linear_attn.qkv_proj
# [8192, 2048], standard layout. make_test.py prints the build command per region.
N = int(os.environ.get("GEMV_N", 8192))
K = int(os.environ.get("GEMV_K", 2048))
RS = int(os.environ.get("GEMV_RS", 2))
N_CORES = int(os.environ.get("GEMV_CORES", 8))
# Output placement: y is written at element offset YOFF of a YTOT-long buffer
# (so two GEMVs can share one output BO -- the firmware rejects runs with
# many buffer args). Default: YOFF = 0, YTOT = N.
YOFF = int(os.environ.get("GEMV_YOFF", 0))
YTOT = int(os.environ.get("GEMV_YTOT", 0)) or (N + YOFF)
PER_CALL = 4          # 4 x 5120 = 20480 B per element, x2 buffered -> 40 KB of L1
NULL = int(os.environ.get("GEMV_NULL", 0))   # 1: DMA-only probe (no arithmetic, y = 0)
EXTRA = os.environ.get("GEMV_CFLAGS", "")        # extra kernel compile flags, e.g. "-O3"


def _include_dirs() -> list[str]:
    from aie.iron.kernels._common import _detect_arch, _include_dirs as base

    inc = base()
    root = Path(config.cxx_header_path()) / "aie_kernels"
    inc.append(str(root))
    inc.append(str(root / _detect_arch()))
    return inc


def ensure_prep_entry(k: int) -> Path:
    """The activation prep entry point for K = k: gemv_q4_prep_k{k}(x, tab)."""
    p = HERE / f"gemv_q4_prep_k{k}.cc"
    src = (
        f"// GENERATED by gemv_q4.py: block-quantise a bf16[{k}] activation into the GEMV table.\n"
        f'#include "gemv_q4.h"\n\n'
        f'extern "C" {{\n'
        f"GEMV_Q4_PREP_ENTRY({k})\n"
        f"}}\n"
    )
    if not p.is_file() or p.read_text(encoding="utf-8") != src:
        p.write_text(src, encoding="utf-8", newline="\n")
    return p


def tab_bytes(k: int) -> int:
    """gemv_q4_tab_bytes(K): int16 xi[K] | int32 s[K/32] | bf16 xs_hi[K/32] | bf16 xs_lo[K/32]."""
    return 2 * k + k // 8 + k // 8


def ensure_entry_points(n_entry: int, per_call: int, per_band: int, rs: int) -> list[Path]:
    """One .cc per entry point (IRON compiles the source once per ExternalFunction;
    several entry points in one TU would each define every symbol)."""
    out = []
    for i in range(n_entry):
        p = HERE / f"gemv_q4_p{per_call}b{per_band}r{rs}_k{i}.cc"
        src = (
            f"// GENERATED by gemv_q4.py: band chunk group {i} "
            f"(chunks {i * per_call}..{(i + 1) * per_call - 1} of a {per_band}-chunk band, "
            f"row split {rs}).\n"
            f"#define GEMV_PER_CALL {per_call}\n"
            f"#define GEMV_PER_BAND {per_band}\n"
            f"#define GEMV_ROWSPLIT {rs}\n"
            f'#include "gemv_q4.h"\n\n'
            f'extern "C" {{\n'
            f"GEMV_Q4_ENTRY({i})\n"
            f"}}\n"
        )
        if not p.is_file() or p.read_text(encoding="utf-8") != src:
            p.write_text(src, encoding="utf-8", newline="\n")
        out.append(p)
    return out


@iron.jit(aiecc_flags=["--alloc-scheme=basic-sequential"])
def gemv_q4(w: In, x: In, y: Out, *, n: CompileTime[int], k: CompileTime[int],
            rs: CompileTime[int], n_cores: CompileTime[int], per_call: CompileTime[int],
            yoff: CompileTime[int] = 0, ytot: CompileTime[int] = 0,
            null: CompileTime[int] = 0, srchash: CompileTime[int] = 0,
            cflags: CompileTime[str] = ""):
    band_rows = 32 * rs
    per_band = rs * k // 256                # chunks per band
    n_entry = per_band // per_call
    assert per_band % per_call == 0
    bands = n // band_rows
    assert n % band_rows == 0 and bands % n_cores == 0
    bands_per_core = bands // n_cores
    band_bytes = per_band * TILE_BYTES
    call_bytes = per_call * TILE_BYTES

    srcs = ensure_entry_points(n_entry, per_call, per_band, rs)
    prep_src = ensure_prep_entry(k)
    elem_ty = np.ndarray[(call_bytes,), np.dtype[np.uint8]]
    x_ty = np.ndarray[(k,), np.dtype[bfloat16]]
    tab_ty = np.ndarray[(tab_bytes(k),), np.dtype[np.uint8]]
    acc_ty = np.ndarray[(band_rows,), np.dtype[np.float32]]
    w_ty = np.ndarray[(bands * band_bytes,), np.dtype[np.uint8]]
    y_total = ytot or (n + yoff)
    y_ty = np.ndarray[(y_total,), np.dtype[np.float32]]

    kernels = [
        ExternalFunction(
            f"gemv_q4_p{per_call}b{per_band}r{rs}_k{i}",
            source_file=str(srcs[i]),
            arg_types=[elem_ty, tab_ty, acc_ty],
            include_dirs=_include_dirs(),
            compile_flags=(["-DGEMV_NULL"] if null else []) + cflags.split(),
        )
        for i in range(n_entry)
    ]
    prep = ExternalFunction(f"gemv_q4_prep_k{k}", source_file=str(prep_src), arg_types=[x_ty, tab_ty],
                            include_dirs=_include_dirs(), compile_flags=cflags.split())

    of_w = [ObjectFifo(elem_ty, name=f"w{c}", depth=2) for c in range(n_cores)]
    of_y = [ObjectFifo(acc_ty, name=f"y{c}", depth=2) for c in range(n_cores)]
    of_x = ObjectFifo(x_ty, name="x", depth=1)      # one activation, broadcast

    def core_body(win, xin, yout, tab, fprep, *ks):
        xe = xin.acquire(1)
        fprep(xe, tab)
        for _ in range_(bands_per_core):
            ye = yout.acquire(1)
            for fn in ks:
                we = win.acquire(1)
                fn(we, tab, ye)
                win.release(1)
            yout.release(1)
        xin.release(1)

    workers = [
        Worker(core_body,
               fn_args=[of_w[c].cons(), of_x.cons(), of_y[c].prod(), Buffer(tab_ty, name=f"tab{c}"), prep, *kernels],
               stack_size=0x1000)
        for c in range(n_cores)
    ]

    w_taps = TensorTiler2D.simple_tiler((1, bands * band_bytes), (1, bands_per_core * band_bytes))
    y_taps = [TensorAccessPattern((1, y_total), yoff + c * bands_per_core * band_rows,
                                  [1, 1, 1, bands_per_core * band_rows], [0, 0, 0, 1]) for c in range(n_cores)]

    def sequence(a_w, a_x, c_y, w_prods, x_prod, y_conss):
        tg = TaskGroup()
        x_prod.fill(a_x, group=tg)
        for c in range(n_cores):
            w_prods[c].fill(a_w, tap=w_taps[c], group=tg)
            y_conss[c].drain(c_y, tap=y_taps[c], wait=True, group=tg)
        tg.finish()

    rt = Runtime(sequence, [w_ty, x_ty, y_ty,
                            [f.prod() for f in of_w], of_x.prod(), [f.cons() for f in of_y]])
    return Program(iron.get_current_device(), rt, workers=workers).resolve_program()


DESIGN = gemv_q4
# srchash: the jit design cache is keyed on this file + CompileTime args only,
# so header edits must change a CompileTime arg to force a rebuild.
_SRCHASH = int(hashlib.sha1((HERE / "gemv_q4.h").read_bytes()).hexdigest()[:8], 16)
SPECIALIZE = {"n": N, "k": K, "rs": RS, "n_cores": N_CORES, "per_call": PER_CALL, "yoff": YOFF, "ytot": YTOT,
              "null": NULL, "srchash": _SRCHASH, "cflags": EXTRA}
